site_name: 线性代数课本重制计划
docs_dir: content
theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: blue
  font:
    text: Noto Sans
    code: Source Code Pro
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - static/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - static/css/extra.css
nav:
- index.md
- 相似矩阵:
  - similarity/introduction.md
  - similarity/concept.md
  - similarity/eigen.md
  - similarity/inner-product.md
  - similarity/unitary.md
  - similarity/reminder.md
- 二次型:
  - quadratic-form/introduction.md
  - quadratic-form/matrix.md
